import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { ToastProvider } from "./context/ToastContext";
import { LoadingProvider } from "./context/LoadingContext";
import { LoadingBar } from "./components/LoadingBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

/**
 * Root layout component that wraps the entire application.
 * It includes global styles, a navbar, and a ToastProvider for toast notifications.
 * @param {LayoutProps} props - Contains children elements to be rendered within the layout.
 * @returns JSX.Element - The main layout with global providers and components.
 */
export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <head>
        <title>Expense Tracker</title>
        <meta
          name="description"
          content="A simple expense tracker application"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LoadingProvider>
          <ToastProvider> 
            <LoadingBar /> {/* Loading bar at the top of the page */}
            <Navbar />
            <main className="container my-4">{children}</main>
          </ToastProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
